import jsPDF from 'jspdf';
import type { StudyItem, Chapter, Topic } from '@/types';

export async function exportItemsToPDF(
  items: StudyItem[],
  title: string,
  chapter?: Chapter,
  topic?: Topic
): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let y = margin;
  
  // Header
  pdf.setFillColor(0, 112, 160);
  pdf.rect(0, 0, pageWidth, 40, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, margin, 25);
  
  if (chapter) {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Chapter: ${chapter.title}`, margin, 35);
  }
  
  if (topic) {
    pdf.text(`Topic: ${topic.title}`, margin + 60, 35);
  }
  
  y = 50;
  
  // Items
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    
    // Check if we need a new page
    if (y > pageHeight - 60) {
      pdf.addPage();
      y = margin;
    }
    
    // Item header with type badge
    const typeColors: Record<string, [number, number, number]> = {
      molecule: [0, 112, 160],
      enzyme: [16, 185, 129],
      medication: [239, 68, 68]
    };
    
    const color = typeColors[item.type] || [100, 100, 100];
    pdf.setFillColor(color[0], color[1], color[2]);
    pdf.roundedRect(margin, y, 30, 8, 2, 2, 'F');
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'bold');
    pdf.text(item.type.toUpperCase(), margin + 4, y + 5.5);
    
    // Item name
    pdf.setTextColor(31, 31, 31);
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text(item.name, margin + 35, y + 6);
    
    y += 15;
    
    // Description
    if (item.description) {
      pdf.setTextColor(98, 106, 114);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      
      const descLines = pdf.splitTextToSize(item.description, pageWidth - 2 * margin);
      pdf.text(descLines, margin, y);
      y += descLines.length * 5 + 5;
    }
    
    // Structure description
    if (item.structure_description) {
      pdf.setTextColor(31, 31, 31);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Structure:', margin, y);
      y += 6;
      
      pdf.setTextColor(98, 106, 114);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      
      const structLines = pdf.splitTextToSize(item.structure_description, pageWidth - 2 * margin);
      pdf.text(structLines, margin, y);
      y += structLines.length * 4 + 5;
    }
    
    // Mechanism
    if (item.mechanism_description) {
      pdf.setTextColor(31, 31, 31);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Mechanism of Action:', margin, y);
      y += 6;
      
      pdf.setTextColor(98, 106, 114);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      
      const mechLines = pdf.splitTextToSize(item.mechanism_description, pageWidth - 2 * margin);
      pdf.text(mechLines, margin, y);
      y += mechLines.length * 4 + 5;
    }
    
    // Uses
    if (item.uses) {
      pdf.setTextColor(31, 31, 31);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Uses:', margin, y);
      y += 6;
      
      pdf.setTextColor(98, 106, 114);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      
      const usesLines = pdf.splitTextToSize(item.uses, pageWidth - 2 * margin);
      pdf.text(usesLines, margin, y);
      y += usesLines.length * 4 + 5;
    }
    
    // Effects
    if (item.effects) {
      pdf.setTextColor(31, 31, 31);
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Effects:', margin, y);
      y += 6;
      
      pdf.setTextColor(98, 106, 114);
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      
      const effectsLines = pdf.splitTextToSize(item.effects, pageWidth - 2 * margin);
      pdf.text(effectsLines, margin, y);
      y += effectsLines.length * 4 + 5;
    }
    
    // Separator
    if (i < items.length - 1) {
      pdf.setDrawColor(200, 205, 216);
      pdf.line(margin, y, pageWidth - margin, y);
      y += 10;
    }
  }
  
  // Footer
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page ${i} of ${totalPages} - Generated by PharmaStudy`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }
  
  pdf.save(`${title.replace(/\s+/g, '_')}.pdf`);
}
